from .coordination_grid import (
    CoordinationGrid,
    State,
    Actions,
    Allocations,
    Messages,           # backward-compat alias for Allocations
    encode_ego,
    decode_ego,
    N_MOVES,
    N_ALLOCATIONS,
    N_MESSAGES,         # backward-compat alias for N_ALLOCATIONS
    N_EGO_ACTIONS,
    GOAL_UNSET,
    GOAL_RED,
    GOAL_BLUE,
    LEGAL_ACTION_IDS_T0,
    LEGAL_ACTION_IDS_TGEQ1,
    ACTION_MASK_T0,
    ACTION_MASK_TGEQ1,
    COMM_ACTION_ONLY,
    COMM_CONDITIONS,
    CAPABILITY_VALUES,
    TRAINING_CAPABILITY_PAIRS,
    HELDOUT_CAPABILITY_PAIRS,
    ALL_CAPABILITY_PAIRS,
    bfs_distance_map,
)
