# "LR": 2.5e-4
"LR": 2.5e-3
"NUM_ENVS": 16
"NUM_STEPS": 128
"TOTAL_TIMESTEPS": 1.5e7 # 5e6
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"REW_SHAPING_HORIZON": 0.5e7 # 2.5e6
"REW_SHAPING_FACTOR": 1 # 0 = no reward shaping, 1 = reward shaping
"ACTIVATION": "tanh"

"ENV_NAME": "overcooked_v2"
"ENV_KWARGS": 
  "layout" : "cramped_room_v4"
  "random_reset": True
  "recipes": ["11"] # 11 = 1-onion-0-tomato, 12 = 2-onion-0-tomato etc 
  "max_steps": 400
  # OO = 12, TT = 15, OT = 17


"LOAD_MODEL": True
"LOAD_MODEL_NAME": "ff_cramped_room_v4_onion"


"MLP_LOAD_MODEL": True
"MLP_LOAD_MODEL_NAME": "random_cramped_room_v4_ff"

"SAVE_MODEL": False
"SEED": 1
"SAVE_MODEL_NAME": "random_cramped_room_v4_ff"

"EXPERIMENT_1": False
"EXP1_MODEL_1": "ff_fivebyfive_v1_v3_onion"
"EXP1_MODEL_2": "ff_fivebyfive_v1_v3_plate"


"NOTE": "train FF"

# Order: [PUT_ONION_IN_POT_REW, PUT_TOMATO_IN_POT_REW, START_COOKING_REW, SOUP_PICKUP_REWARD, SOUP_DELIVERY_REWARD, MAIN_REW_IS_SHAPED_REW] = [1,1,1,1,20]
REW_SHAPING_PARAMS_AGENT_0: [1, 1, 1, 1, 20]
REW_SHAPING_PARAMS_AGENT_1: [1, 1, 1, 1, 20]
# REW_SHAPING_PARAMS_AGENT_0: [-10, -10, -10, 1, 1]
# REW_SHAPING_PARAMS_AGENT_1: [1, 1, 1, -10, -10]

MAIN_REW_IS_SHAPED_REW: False

"LOAD_MODEL_AGENT_0_INIT": False
"LOAD_MODEL_AGENT_0_INIT_NAME": ""


"RANDOM_WAIT_PROBABILITY_AGENT_0": 0
"RANDOM_TRAIN_AGENT_0_PERCENTAGE": 0
"RANDOM_TRAIN_AGENT_1_PERCENTAGE": 0
"RANDOM_ROLLOUT_AGENT_1": False

"ANNEAL_LR": True
"NUM_SEEDS": 1
"RND_SCALE": 0.1
"SHARED_PARAMETERS": True
"WAIT_PROB_0": 0
"WAIT_PROB_1": 0
# "layouts": []

# WandB Params
"ENTITY": ""
"PROJECT": ""
"WANDB_MODE" : "offline"
