"REW_SHAPING_FACTOR": 1
"ENV_NAME": "overcooked"
"ENV_KWARGS": 
  "layout" : "counter_circuit"
  # "recipes": ["13"]

"LR": 5e-4
"ANNEAL_LR": True
"LR_WARMUP": 0.05

"NUM_ENVS": 256 # 1024 # 256
"NUM_STEPS": 256 # 1024 # 256
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 64 # 256 # 64

"TOTAL_TIMESTEPS": 1e7
"REW_SHAPING_HORIZON": 2.5e6

"FC_DIM_SIZE": 128
"GRU_HIDDEN_DIM": 128

"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"SCALE_CLIP_EPS": False
"VF_COEF": 1.0
"MAX_GRAD_NORM": 0.25
"ACTIVATION": "relu"
"SEED": 0
"NUM_SEEDS": 4
"SHARED_PARAMETERS": True

# WandB Params
"ENTITY": ""
"PROJECT": "jaxmarl-overcooked"
"WANDB_MODE" : "offline"