"LR": 2.5e-4
"NUM_ENVS": 16
"NUM_STEPS": 128
"TOTAL_TIMESTEPS": 3e3
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "tanh"
"ENV_NAME": "MPE_simple_spread_v3"
# "ENV_KWARGS": {
#                'num_agents': 5,
#                'num_landmarks':2,
#               }
"ENV_KWARGS": {
              }
"ANNEAL_LR": True
"SEED": 106
"NUM_SEEDS": 1
"SAVE_MODEL_NAME": "MPE_simple_spread_v3"

# WandB Params
"ENTITY": ""
"PROJECT": "jaxmarl-mpe"
"WANDB_MODE" : "offline"